apiVersion: v1
kind: Service
metadata:
  name: megafactory-sql
  namespace: default
  labels:
    app: megafactory-sql
spec:
  type: NodePort
  selector:
    app: megafactory-sql
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      name: http
